### ISSUE TITLE
Remove bundled dependencies as they are not needed

### ISSUE THREAD

**Issue by adnanrahic** [adnanrahic/node-gcstats#1]
Bundled dependencies should not be necessary anymore: https://github.com/mapbox/node-pre-gyp#configuring
https://github.com/adnanrahic/node-gcstats/blob/master/package.json#L35

Thanks @gjasny for letting me know!

**Comment by rohitkumarcs** [comment]
@adnanrahic

I see bundled dependencies still refers to "node-pre-gyp" after your latest merge to use @mapbox/node-pre-gyp. 
Can we also replace it with @mapbox/node-pre-gyp in bundled dependencies also if not removing it all together? This will remove "node-pre-gyp" completely from module.

**Comment by Ghazgkull** [comment]
@adnanrahic @rohitkumarcs I went ahead and put together a PR to do this: https://github.com/adnanrahic/node-gcstats/pull/6

**Comment by adnanrahic** [comment]
This is a lovely PR. Thanks for taking a look. I just didn't have the bandwidth to check it out before now. :bow:
