### ISSUE TITLE
Update dependency (Node security advisory 1004946)

### ISSUE THREAD

**Issue by JNPLZ** [adnanrahic/node-gcstats#7]
Hi there,

ther ist a security issue in the dependencies (https://github.com/advisories/GHSA-93q8-gq69-wqmw):
@sematext/gc-stats>@mapbox/node-pre-gyp>npmlog>gauge>wide-align>string-width>strip-ansi>ansi-regex

Could you please update them?
Thanks a lot!

**Comment by adnanrahic** [comment]
Thanks for bringing this up. I'm no longer actively maintaining this. Could you maybe provide a PR with the updated dependencies? I could review the PR and merge it. :slightly_smiling_face:

**Comment by JNPLZ** [comment]
All right, thanks! I've just created the pull request: https://github.com/adnanrahic/node-gcstats/pull/8

**Comment by adnanrahic** [comment]
Nice! I've merged the PR.
